name: Security Updates

on:
  schedule:
    # Run every Monday at 9am UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  update-dependencies:
    name: Update Go Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: true
    
    - name: Update Go modules
      run: |
        go get -u ./...
        go mod tidy
    
    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
    
    - name: Update vendor hash if needed
      run: |
        # Set vendorHash to empty string to force error with correct hash
        sed -i 's/vendorHash = ".*"/vendorHash = ""/' flake.nix
        
        # Try to build, which will fail but give us the correct hash
        if ! nix build 2>&1 | tee build.log; then
          # Extract the correct hash from the error message
          CORRECT_HASH=$(grep -oE 'got:[[:space:]]+sha256-[a-zA-Z0-9+/]+' build.log | sed 's/got:[[:space:]]*//;s/^[[:space:]]*//')
          
          if [ -n "$CORRECT_HASH" ]; then
            # Update flake.nix with the correct hash
            sed -i "s/vendorHash = \"\"/vendorHash = \"$CORRECT_HASH\"/" flake.nix
            echo "Updated vendorHash to: $CORRECT_HASH"
          fi
        fi
    
    - name: Run security audit with govulncheck
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck ./...
      continue-on-error: true
    
    - name: Run Nancy security scan
      uses: sonatype-nexus-community/nancy-github-action@main
      continue-on-error: true
    
    - name: Check if changes exist
      id: changes
      run: |
        git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT
    
    - name: Create Pull Request
      if: steps.changes.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore(deps): update go dependencies'
        title: 'chore(deps): Automated Go dependency updates'
        body: |
          ## Automated Dependency Update
          
          This PR contains automated updates to Go module dependencies.
          
          ### Security Scans
          - govulncheck has been run to check for known vulnerabilities
          - Nancy scan has been performed
          
          ### What's Changed
          - Updated Go module dependencies to their latest versions
          - Ran `go mod tidy` to clean up dependencies
          
          Please review the changes and ensure all tests pass before merging.
        branch: automated-go-updates
        delete-branch: true
        labels: |
          dependencies
          automated
          security
    
    - name: Enable auto-merge
      if: steps.changes.outputs.changes == 'true'
      run: |
        gh pr merge --auto --squash "${{ steps.create-pr.outputs.pull-request-number }}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-nix-dependencies:
    name: Update Nix Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
    
    - name: Update Nix flake
      run: |
        nix flake update
    
    - name: Check if changes exist
      id: changes
      run: |
        git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT
    
    - name: Create Pull Request
      if: steps.changes.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore(deps): update nix flake inputs'
        title: 'chore(deps): Automated Nix flake updates'
        body: |
          ## Automated Nix Flake Update
          
          This PR contains automated updates to Nix flake inputs.
          
          ### What's Changed
          - Updated flake.lock with latest input versions
          
          Please review the changes and ensure the build succeeds before merging.
        branch: automated-nix-updates
        delete-branch: true
        labels: |
          dependencies
          automated
          nix