name: Security Updates

on:
  schedule:
    # Run every Monday at 9am UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  update-all-dependencies:
    name: Update All Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.24'
        cache: true
    
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    
    - name: Setup Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    
    - name: Update Go modules
      run: |
        go get -u ./...
        go mod tidy
    
    - name: Update Nix flake
      run: |
        nix flake update
    
    - name: Update vendor hash if needed
      shell: bash
      run: |
        set -euo pipefail
        
        echo "Checking vendor hash..."
        
        # First check if current hash is valid
        if nix build .#default.goModules --no-link 2>&1 | tee build.log; then
          echo "✅ Vendor hash is already valid"
        else
          # Check if it's a hash mismatch
          if grep -qE "(hash mismatch|invalid SRI hash)" build.log; then
            echo "❌ Vendor hash needs updating"
            
            # Set to empty to get correct hash
            sed -i 's|vendorHash = ".*"|vendorHash = ""|' flake.nix
            
            # Get the correct hash
            if ! nix build 2>&1 | tee build.log; then
              CORRECT_HASH=$(grep -oE 'got:[[:space:]]+sha256-[a-zA-Z0-9+/]+' build.log | sed 's/got:[[:space:]]*//' | sed 's/^[[:space:]]*//')
              
              if [ -z "$CORRECT_HASH" ]; then
                echo "Failed to extract vendor hash from build output"
                echo "Build log tail:"
                tail -20 build.log
                exit 1
              fi
              
              echo "Found correct hash: $CORRECT_HASH"
              
              # Update flake.nix with the correct hash
              sed -i "s|vendorHash = \"\"|vendorHash = \"$CORRECT_HASH\"|" flake.nix
              
              # Verify the build now works
              echo "Verifying build with new hash..."
              if ! nix build; then
                echo "Build still fails after hash update"
                exit 1
              fi
              
              echo "✅ Successfully updated vendorHash"
            fi
          else
            echo "Build failed for reasons other than hash mismatch"
            tail -20 build.log
            exit 1
          fi
        fi
    
    - name: Run security audit with govulncheck
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck ./...
      continue-on-error: true
    
    - name: Run Nancy security scan
      uses: sonatype-nexus-community/nancy-github-action@main
      continue-on-error: true
    
    - name: Stage all changes
      run: |
        echo "Files modified before staging:"
        git status --porcelain
        git add -A
        echo "Files staged:"
        git diff --cached --name-only
    
    - name: Check if changes exist
      id: changes
      run: |
        git diff --cached --exit-code || echo "changes=true" >> $GITHUB_OUTPUT
    
    - name: Create Pull Request
      if: steps.changes.outputs.changes == 'true'
      id: create-pr
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore(deps): update all dependencies

- Updated Go module dependencies
- Updated Nix flake inputs
- Updated vendorHash for Nix build'
        title: 'chore(deps): Automated dependency updates (Go + Nix)'
        body: |
          ## Automated Dependency Update
          
          This PR contains automated updates to all project dependencies.
          
          ### What's Changed
          - Updated Go module dependencies to their latest versions
          - Updated Nix flake.lock with latest nixpkgs and other inputs
          - Updated vendorHash in flake.nix to match new Go dependencies
          - Ran `go mod tidy` to clean up dependencies
          
          ### Security Scans
          - govulncheck has been run to check for known vulnerabilities
          - Nancy scan has been performed
          
          Please review the changes and ensure all tests pass before merging.
        branch: automated-dependency-updates
        delete-branch: true
        labels: |
          dependencies
          automated
          security
          go
          nix
    
    - name: Enable auto-merge
      if: steps.changes.outputs.changes == 'true' && steps.create-pr.outputs.pull-request-number
      run: |
        gh pr merge --auto --squash "${{ steps.create-pr.outputs.pull-request-number }}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}